server:
  address: localhost
  port: 8080
  servlet:
    encoding: #Encoding UTF-8
      charset: UTF-8
      enabled: true
      force: true

spring:
  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource: #mysql datasource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/cbot?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: springer
    password: springer